// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DirectOne - Premium Products Direct to You | UK Online Store",
  description: "Shop premium quality products with fast UK delivery. Trusted by 50,000+ customers. Free delivery over £50, 30-day returns, secure payments.",
  keywords: "online shopping UK, premium products, fast delivery, secure payments, DirectOne",
  openGraph: {
    title: "DirectOne - Premium Products Direct to You",
    description: "Shop premium quality products with fast UK delivery. Trusted by 50,000+ customers.",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-GB">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}